// <auto-generated />
namespace TaskMgmtSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class CreatenewTableTaskModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatenewTableTaskModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201708071830334_Create new Table TaskModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
